In [60]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [61]:
df = pd.read_csv('Churn_Modelling.csv')
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [63]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [64]:
df.duplicated().sum()

np.int64(0)

In [65]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [66]:
df.drop(columns=['RowNumber','CustomerId','Surname'], inplace=True)

In [67]:
df.head(10)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [68]:
df=pd.get_dummies(df,columns=['Geography','Gender'],drop_first=True, dtype=int)

In [69]:
from sklearn.model_selection import train_test_split
x = df.drop(columns=["Exited"])
y = df['Exited']

x_train , x_test, y_train,y_test = train_test_split(
    x,y,test_size=0.2, random_state=42
)

In [70]:
x_train.shape

(8000, 11)

In [71]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [72]:
!pip install tensorflow

Requirement already satisfied: tensorflow in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (2.21.0)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (2.32.5)
Requirement already satisfied: packaging in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (26.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (7.34.1)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (2.1.2)
Requirement already satisfied: setuptools in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (63.2.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (1.80.0)
Requirement already satisfied: six>=1.12.0 in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: keras>=3.12.0 in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (3.12.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (2.2.6)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.46.3)
Requirement already satisfied: optree in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.12.0->tensorflow) (0.19.0)
Requirement already satisfied: namex in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: rich in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.12.0->tensorflow) (14.3.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.2.25)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\tanvir ishrak\appdata\local\programs\python\python310\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)

[notice] A new release of pip available: 22.2.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [73]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [88]:
model = Sequential()

model.add(Dense(7, activation='relu', input_dim=11))  # 11 because we have 11 columns in x_train.shape
model.add(Dense(3,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

c:\Users\Tanvir Ishrak\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [89]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_17 (Dense)                │ (None, 7)              │            84 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (None, 3)              │            24 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 112 (448.00 B)

 Trainable params: 112 (448.00 B)

 Non-trainable params: 0 (0.00 B)

In [95]:
model.compile(loss='binary_crossentropy', optimizer='Adam',metrics=['accuracy'])

In [109]:
history = model.fit(x_train_scaled,y_train,epochs=100 , validation_split=0.2)  # acccuracy and loss for training data  || val_accuracy/loss for that 20% test data

Epoch 1/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8628 - loss: 0.3290 - val_accuracy: 0.8594 - val_loss: 0.3449
Epoch 2/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8641 - loss: 0.3290 - val_accuracy: 0.8587 - val_loss: 0.3437
Epoch 3/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8631 - loss: 0.3286 - val_accuracy: 0.8606 - val_loss: 0.3450
Epoch 4/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8628 - loss: 0.3290 - val_accuracy: 0.8606 - val_loss: 0.3443
Epoch 5/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8636 - loss: 0.3287 - val_accuracy: 0.8569 - val_loss: 0.3436
Epoch 6/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8636 - loss: 0.3288 - val_accuracy: 0.8606 - val_loss: 0.3440
Epoch 7/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8641 - loss: 0.3290 - val_accuracy: 0.8569 - val_loss: 0.3443
Epoch 8/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8642 - loss: 0.3289 - val_accuracy: 0.8600 - val_loss: 0.3449
Epoch 9/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8644 - loss: 0.3288 - val_accuracy: 0.8606 - val_loss: 0.3439
Epoch 10/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8630 - loss: 0.3289 - val_accuracy: 0.8575 - val_loss: 0.3440
Epoch 11/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8639 - loss: 0.3286 - val_accuracy: 0.8575 - val_loss: 0.3440
Epoch 12/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8642 - loss: 0.3288 - val_accuracy: 0.8575 - val_loss: 0.3440
Epoch 13/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8633 - loss: 0.3288 - val_accuracy: 0.8575 - val_loss: 0.3443
Epoch 14/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8639 - loss: 0.3287 - val_accuracy: 0.8587 - val_loss: 0.3448
Epoch 15/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8628 - loss: 0.3289 - val_accuracy: 0.8594 - val_loss: 0.3436
Epoch 16/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8639 - loss: 0.3288 - val_accuracy: 0.8587 - val_loss: 0.3439
Epoch 17/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8628 - loss: 0.3287 - val_accuracy: 0.8581 - val_loss: 0.3442
Epoch 18/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8633 - loss: 0.3287 - val_accuracy: 0.8562 - val_loss: 0.3436
Epoch 19/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8636 - loss: 0.3287 - val_accuracy: 0.8569 - val_loss: 0.3442
Epoch 20/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8628 - loss: 0.3286 - val_accuracy: 0.8587 - val_loss: 0.3440
Epoch 21/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8633 - loss: 0.3285 - val_accuracy: 0.8581 - val_loss: 0.3446
Epoch 22/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8641 - loss: 0.3286 - val_accuracy: 0.8562 - val_loss: 0.3446
Epoch 23/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8645 - loss: 0.3286 - val_accuracy: 0.8594 - val_loss: 0.3444
Epoch 24/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8631 - loss: 0.3286 - val_accuracy: 0.8562 - val_loss: 0.3443
Epoch 25/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8644 - loss: 0.3286 - val_accuracy: 0.8562 - val_loss: 0.3439
Epoch 26/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8628 - loss: 0.3281 - val_accuracy: 0.8556 - val_loss: 0.3453
Epoch 27/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8647 - loss: 0.3288 - val_accuracy: 0.8569 - val_loss: 0.3445
Epoch 28/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8639 - loss: 0.3287 - val_accuracy: 0.8569 - val_loss: 0.3448
Epoch 29/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8641 - loss: 0.3283 - val_accuracy: 0.8569 - val_loss: 0.3443
Epoch 30/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8636 - loss: 0.3285 - val_accuracy: 0.8569 - val_loss: 0.3443
Epoch 31/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8631 - loss: 0.3286 - val_accuracy: 0.8562 - val_loss: 0.3444
Epoch 32/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8634 - loss: 0.3284 - val_accuracy: 0.8569 - val_loss: 0.3450
Epoch 33/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8628 - loss: 0.3283 - val_accuracy: 0.8575 - val_loss: 0.3440
Epoch 34/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8628 - loss: 0.3285 - val_accuracy: 0.8575 - val_loss: 0.3445
Epoch 35/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8634 - loss: 0.3286 - val_accuracy: 0.8575 - val_loss: 0.3447
Epoch 36/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8628 - loss: 0.3283 - val_accuracy: 0.8594 - val_loss: 0.3446
Epoch 37/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8642 - loss: 0.3285 - val_accuracy: 0.8581 - val_loss: 0.3451
Epoch 38/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8631 - loss: 0.3284 - val_accuracy: 0.8581 - val_loss: 0.3453
Epoch 39/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8637 - loss: 0.3282 - val_accuracy: 0.8575 - val_loss: 0.3443
Epoch 40/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8627 - loss: 0.3283 - val_accuracy: 0.8575 - val_loss: 0.3451
Epoch 41/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8630 - loss: 0.3282 - val_accuracy: 0.8581 - val_loss: 0.3448
Epoch 42/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8631 - loss: 0.3284 - val_accuracy: 0.8575 - val_loss: 0.3448
Epoch 43/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8630 - loss: 0.3284 - val_accuracy: 0.8581 - val_loss: 0.3450
Epoch 44/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8644 - loss: 0.3281 - val_accuracy: 0.8562 - val_loss: 0.3453
Epoch 45/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8631 - loss: 0.3286 - val_accuracy: 0.8581 - val_loss: 0.3451
Epoch 46/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8634 - loss: 0.3285 - val_accuracy: 0.8575 - val_loss: 0.3446
Epoch 47/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8630 - loss: 0.3283 - val_accuracy: 0.8594 - val_loss: 0.3445
Epoch 48/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8639 - loss: 0.3283 - val_accuracy: 0.8556 - val_loss: 0.3445
Epoch 49/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8644 - loss: 0.3282 - val_accuracy: 0.8600 - val_loss: 0.3452
Epoch 50/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8634 - loss: 0.3283 - val_accuracy: 0.8562 - val_loss: 0.3447
Epoch 51/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8634 - loss: 0.3280 - val_accuracy: 0.8575 - val_loss: 0.3452
Epoch 52/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8625 - loss: 0.3283 - val_accuracy: 0.8575 - val_loss: 0.3452
Epoch 53/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8628 - loss: 0.3283 - val_accuracy: 0.8569 - val_loss: 0.3451
Epoch 54/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8631 - loss: 0.3283 - val_accuracy: 0.8594 - val_loss: 0.3448
Epoch 55/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8636 - loss: 0.3283 - val_accuracy: 0.8581 - val_loss: 0.3449
Epoch 56/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8631 - loss: 0.3282 - val_accuracy: 0.8575 - val_loss: 0.3448
Epoch 57/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8620 - loss: 0.3282 - val_accuracy: 0.8581 - val_loss: 0.3455
Epoch 58/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8622 - loss: 0.3280 - val_accuracy: 0.8594 - val_loss: 0.3452
Epoch 59/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8620 - loss: 0.3285 - val_accuracy: 0.8581 - val_loss: 0.3453
Epoch 60/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8634 - loss: 0.3283 - val_accuracy: 0.8594 - val_loss: 0.3458
Epoch 61/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8639 - loss: 0.3282 - val_accuracy: 0.8587 - val_loss: 0.3455
Epoch 62/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8637 - loss: 0.3280 - val_accuracy: 0.8562 - val_loss: 0.3456
Epoch 63/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8636 - loss: 0.3280 - val_accuracy: 0.8581 - val_loss: 0.3450
Epoch 64/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8631 - loss: 0.3278 - val_accuracy: 0.8581 - val_loss: 0.3450
Epoch 65/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8634 - loss: 0.3281 - val_accuracy: 0.8600 - val_loss: 0.3454
Epoch 66/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8627 - loss: 0.3280 - val_accuracy: 0.8606 - val_loss: 0.3453
Epoch 67/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8630 - loss: 0.3281 - val_accuracy: 0.8581 - val_loss: 0.3458
Epoch 68/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8637 - loss: 0.3280 - val_accuracy: 0.8594 - val_loss: 0.3453
Epoch 69/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8636 - loss: 0.3278 - val_accuracy: 0.8587 - val_loss: 0.3455
Epoch 70/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8623 - loss: 0.3284 - val_accuracy: 0.8575 - val_loss: 0.3457
Epoch 71/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8623 - loss: 0.3280 - val_accuracy: 0.8575 - val_loss: 0.3451
Epoch 72/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8637 - loss: 0.3281 - val_accuracy: 0.8587 - val_loss: 0.3450
Epoch 73/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8639 - loss: 0.3281 - val_accuracy: 0.8581 - val_loss: 0.3451
Epoch 74/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8619 - loss: 0.3279 - val_accuracy: 0.8556 - val_loss: 0.3452
Epoch 75/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8634 - loss: 0.3278 - val_accuracy: 0.8562 - val_loss: 0.3452
Epoch 76/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8628 - loss: 0.3277 - val_accuracy: 0.8581 - val_loss: 0.3454
Epoch 77/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8625 - loss: 0.3278 - val_accuracy: 0.8581 - val_loss: 0.3453
Epoch 78/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8631 - loss: 0.3280 - val_accuracy: 0.8575 - val_loss: 0.3453
Epoch 79/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8637 - loss: 0.3277 - val_accuracy: 0.8594 - val_loss: 0.3458
Epoch 80/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8636 - loss: 0.3279 - val_accuracy: 0.8600 - val_loss: 0.3454
Epoch 81/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8639 - loss: 0.3277 - val_accuracy: 0.8581 - val_loss: 0.3451
Epoch 82/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8633 - loss: 0.3278 - val_accuracy: 0.8581 - val_loss: 0.3448
Epoch 83/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8639 - loss: 0.3279 - val_accuracy: 0.8569 - val_loss: 0.3459
Epoch 84/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8625 - loss: 0.3277 - val_accuracy: 0.8587 - val_loss: 0.3454
Epoch 85/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8631 - loss: 0.3279 - val_accuracy: 0.8594 - val_loss: 0.3450
Epoch 86/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8633 - loss: 0.3278 - val_accuracy: 0.8575 - val_loss: 0.3463
Epoch 87/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8641 - loss: 0.3278 - val_accuracy: 0.8594 - val_loss: 0.3453
Epoch 88/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8617 - loss: 0.3277 - val_accuracy: 0.8575 - val_loss: 0.3455
Epoch 89/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8653 - loss: 0.3275 - val_accuracy: 0.8594 - val_loss: 0.3453
Epoch 90/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8647 - loss: 0.3277 - val_accuracy: 0.8587 - val_loss: 0.3454
Epoch 91/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8641 - loss: 0.3280 - val_accuracy: 0.8569 - val_loss: 0.3461
Epoch 92/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8644 - loss: 0.3278 - val_accuracy: 0.8600 - val_loss: 0.3458
Epoch 93/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8636 - loss: 0.3278 - val_accuracy: 0.8575 - val_loss: 0.3458
Epoch 94/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8622 - loss: 0.3277 - val_accuracy: 0.8600 - val_loss: 0.3457
Epoch 95/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8634 - loss: 0.3278 - val_accuracy: 0.8575 - val_loss: 0.3459
Epoch 96/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8606 - loss: 0.3274 - val_accuracy: 0.8569 - val_loss: 0.3458
Epoch 97/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8641 - loss: 0.3278 - val_accuracy: 0.8569 - val_loss: 0.3458
Epoch 98/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8639 - loss: 0.3278 - val_accuracy: 0.8569 - val_loss: 0.3454
Epoch 99/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8653 - loss: 0.3279 - val_accuracy: 0.8575 - val_loss: 0.3457
Epoch 100/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8633 - loss: 0.3276 - val_accuracy: 0.8562 - val_loss: 0.3459

In [110]:
model.layers[1].get_weights()

[array([[-0.4147183 ,  0.70738   , -0.24326572],
        [ 1.0713761 ,  0.7847828 , -1.5301912 ],
        [-0.6419649 ,  0.8607627 ,  0.17082146],
        [ 1.2121747 ,  0.7815149 , -0.67754626],
        [-0.16674602,  1.4370403 , -0.93004215],
        [-1.2418617 , -0.6186419 , -0.9348566 ],
        [-0.87672514, -0.34058753, -2.205718  ]], dtype=float32),
 array([-0.7240335,  0.4238139,  0.8701964], dtype=float32)]

In [111]:
y_log = model.predict(x_test_scaled)

y_pred = np.where(y_log>0.5 , 1,0)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [112]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_pred)

0.861