In [21]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [22]:
class Perceptron:
    def __init__(self, eta, epochs):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta
        self.epochs = epochs
    
    def activationFunction(self , inputs, weights):
        z = np.dot(inputs , weights)
        return np.where(z>0 , 1 ,0)
    
    def fit(self, x,y):
        self.x = x
        self.y = y
        
        x_with_bias = np.c_[self.x , -np.ones((len(self.x),1))]
        print(f'x_with_bias: {x_with_bias}')
        
        
        for epoch in range(self.epochs):
            print('Epoch: ',epoch)
        
            y_hat = self.activationFunction(x_with_bias, self.weights)
            print(f'Predicted value {y_hat}')
            
            error = self.y - y_hat
            print(f'Error: {error}')
            
            # weight update
            self.weights = self.weights + self.eta * np.dot(x_with_bias.T,error)
            print(f'Updated weight : {self.weights}')
            
            print('###########')
        
        
    def predict(self,x):
        x_with_bias = np.c_[x,-np.ones((len(x),1))]
        
        return self.activationFunction(x_with_bias , self.weights)

In [23]:
import pandas as pd

data = {
    'x1':[0,0,1,1],
    'x2':[0,1,0,1],
    'y':[0,0,0,1]
}
AND = pd.DataFrame(data)
x = AND.drop('y',axis=1)
y= AND['y']
y.to_frame()

   y
0  0
1  0
2  0
3  1

## Model prediction

In [24]:
model = Perceptron(eta=0.5,epochs=10)
model.fit(x,y)

x_with_bias: [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Epoch:  0
Predicted value [1 1 1 1]
Error: 0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated weight : [-0.49993523 -0.4998477   1.49997658]
###########
Epoch:  1
Predicted value [0 0 0 0]
Error: 0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weight : [6.47688538e-05 1.52302986e-04 9.99976585e-01]
###########
Epoch:  2
Predicted value [0 0 0 0]
Error: 0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weight : [0.50006477 0.5001523  0.49997658]
###########
Epoch:  3
Predicted value [0 1 1 1]
Error: 0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated weight : [6.47688538e-05 1.52302986e-04 1.49997658e+00]
###########
Epoch:  4
Predicted value [0 0 0 0]
Error: 0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weight : [0.50006477 0.5001523  0.99997658]
###########
Epoch:  5
Predicted value [0 0 0 1]
Error: 0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight : [0.50006477 0.5001523  0.99997658]
###########
Epoch:  6
Predicted value [0 0 0 1]
Error: 0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight : [0.50006477 0.5001523  0.99997658]
###########
Epoch:  7
Predicted value [0 0 0 1]
Error: 0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight : [0.50006477 0.5001523  0.99997658]
###########
Epoch:  8
Predicted value [0 0 0 1]
Error: 0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight : [0.50006477 0.5001523  0.99997658]
###########
Epoch:  9
Predicted value [0 0 0 1]
Error: 0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weight : [0.50006477 0.5001523  0.99997658]
###########

### Dot products

In [2]:
import numpy as np

w = np.array([2,2])
x= np.array([2,2])

dot=np.dot(w,x)
dot

np.int64(8)

In [4]:
random = np.random.seed(42)

random_normal=np.random.randn(2)  # "randn" brings both pos and neg vals
random_normal

array([ 0.49671415, -0.1382643 ])

### concatenation

In [7]:
import pandas as pd

data = {
    'x1':[0,0,1,1],
    'x2':[0,1,0,1],
    'y':[0,0,0,1]
}
AND = pd.DataFrame(data)
AND

   x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [8]:
x = AND.drop('y', axis=1)
y = AND['y']
y.to_frame()

   y
0  0
1  0
2  0
3  1

In [20]:
bias = np.c_[x, -np.ones((len(x),1))]  # c_ -> concatenate
bias

array([[ 0.,  0., -1.],
       [ 0.,  1., -1.],
       [ 1.,  0., -1.],
       [ 1.,  1., -1.]])